FROM rust:1.82 as builder

WORKDIR /app
COPY Cargo.toml ./
COPY Cargo.lock ./
COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/algoritm-service /app/app

# Exponer el puerto (ajusta si tu servidor usa otro)
EXPOSE 8088

# Ejecuta el binario
CMD ["./app"]

